### ISSUE TITLE
The payload for events on Events API 2.0 changed - The payload on component need to update

### ISSUE THREAD

**Issue by Beethoven** [managed-components/tiktok#15]
The Events API 2.0 ([/event/track/](https://ads.tiktok.com/marketing_api/docs?id=1771101303285761)) is now the recommended endpoint for reporting events from all sources, including web, app, offline and CRM (Customer relationship management) systems. This endpoint provides a unified API schema to help advertisers simplify and streamline their integration.

https://business-api.tiktok.com/portal/docs?rid=p41a33fdhon&id=1771100779668482

The new payload:
https://business-api.tiktok.com/portal/docs?id=1771100865818625

**Comment by Beethoven** [comment]
The payload doesn't have event_source_id
This is the return of a POST event:

{
    "code": 40002,
    "message": "Invalid value for event_source_id: not a valid string.",
    "request_id": "202406191421063422AF4AE0D8D70D1B6A"
}

**Comment by ad-astra-via** [comment]
Hello @Beethoven would you be able to help us test a PR for this? If so please lemme know how I can reach out ot you! Thanks.

**Comment by Beethoven** [comment]
> Hello @Beethoven would you be able to help us test a PR for this? If so please lemme know how I can reach out ot you! Thanks.

Yse, my email: [robertomedeirosgarcia@gmail.com](mailto:robertomedeirosgarcia@gmail.com)
