### ISSUE TITLE
Properties are always set to empty object

### ISSUE THREAD

**Issue by agcty** [managed-components/tiktok#3]
The getBaseRequestBody function initialises the properties key as an empty object without letting you override it. This makes it impossible to track what products a user has bought, significantly reducing targeting capabilities.

https://github.com/managed-components/tiktok/blob/8227d07d0a16d2229cd76d02dfd2ef569e56ff23/src/track.ts#L45

This is an example of what can be tracked with TikTok but is currently impossible with Zaraz:

```javascript
properties: {
  contents: [
    {
      price: 8,
      quantity: 2,
      content_type: "product_group",
      content_id: "1077218",
    },
    {
      price: 30,
      quantity: 1,
      content_type: "product_group",
      content_id: "1197218",
    },
  ],
  currency: "USD",
  value: 46
}
```

**Comment by bjesus** [comment]
Hey @agcty - this looks like it should be part of adding Ecommerce API support to the component. Do you have any link for the relevant documentation?

**Comment by bjesus** [comment]
I'm closing this as Ecommerce support is part of the component.
